version: "3.9"
   
services:
  pg:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  server:
    build: ./server
    volumes:
      - ./server/app:/app
    ports:
      - "80:80"